pywal: false
i3: false
log: false

key_positions:
  # Define positions for individual keys, the tuple corrsponds to (row, column) of they keyboard as defioned by openrazer
  1_key:
    - (1,1)
  2_key:
    - (1,2)
  3_key:
    - (1,3)
  4_key:
    - (1,4)
  5_key:
    - (1,5)
  6_key:
    - (1,6)
  7_key:
    - (1,7)
  8_key:
    - (1,8)
  9_key:
    - (1,9)
  10_key:
    - (1,10)
  
  # Define positions for special keys
  super: 
    - (5, 1)
  enter: 
    - (3, 13)
  shift:
    - (4, 0)

  # Define groups of keys
  numbers:
    - (1, 1)
    - (1, 2)
    - (1, 3)
    - (1, 4)
    - (1, 5)
    - (1, 6)
    - (1, 7)
    - (1, 8)
    - (1, 9)
    - (1, 10)
  arrows:
    - (5, 14)
    - (5, 15)
    - (5, 16)
    - (4, 15)

modes:
  # Base mode - applied when no keys are pressed
  base:
    rules:
      - keys: [all]
        color: [0,255,0]

  # Single-key modes
  super:
    rules:
      - keys: [numbers]
        color: [255,255,255]
      - keys: [super]
        color: [255, 255, 255]
      - keys: [enter]
        color: [255,255,255]
      - keys: [arrows]
        color: [255,255,255]
      - keys: [shift]
        color: [255, 255, 255]

  # Two-key combination modes are formated as KeyBeingHeld_NewKeyBeingHeld
  super_shift:
    rules:
      - keys: [numbers]
        color: [255,255,255]
      - keys: [super]
        color: [0, 255, 0]
      - keys: [shift]
        color: [255, 255, 255]
      - keys: [arrows]
        color: [0,0,255]

  shift_super:
    rules:
      - keys: [numbers]
        color: [255,255,255]
      - keys: [super]
        color: [0, 255, 0]
      - keys: [shift]
        color: [255, 255, 255]
      - keys: [arrows]
        color: [0,0,255]
  
  alt:
    rules:
      - keys: [1_key]
        color: [188,214,160]
      - keys: [2_key]
        color: [143,143,144]
      - keys: [3_key]
        color: [99,146,152]
      - keys: [4_key]
        color: [57,99,88]
      - keys: [5_key]
        color: [173,74,44]
      - keys: [6_key]
        color: [146,120,150]
      - keys: [7_key]
        color: [93,185,213]
      - keys: [8_key]
        color: [38,52,115]
      - keys: [9_key]
        color: [43,86,138]
      - keys: [10_key]
        color: [131,97,130]
